compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

enableImmutableInstalls: false

nodeLinker: node-modules

packageExtensions:
  'commitizen@*':
    dependencies:
      'cz-conventional-changelog': '*'
